version: '3'

secrets:
  mysql_database:
    file: ../secrets/mysql_database.txt
  mysql_password:
    file: ../secrets/mysql_password.txt
  mysql_root_password:
    file: ../secrets/mysql_root_password.txt
  mysql_user:
    file: ../secrets/mysql_user.txt
  wp_admin_email:
    file: ../secrets/wp_admin_email.txt
  wp_admin_password:
    file: ../secrets/wp_admin_password.txt
  wp_admin_user:
    file: ../secrets/wp_admin_user.txt
  wp_user_email:
    file: ../secrets/wp_user_email.txt
  wp_user_password:
    file: ../secrets/wp_user_password.txt
  wp_user:
    file: ../secrets/wp_user_user.txt

services:
  mariadb:
    build:
      context: ./requirements/mariadb
    image: mariadb
    container_name: mariadb
    restart: always
    volumes:
      - mariadb_vol:/var/lib/mysql
    networks:
      - inception_network
    env_file:
      - .env
    secrets:
      - mysql_database
      - mysql_password
      - mysql_root_password
      - mysql_user

  wordpress:
    build:
      context: ./requirements/wordpress
    image: wordpress
    container_name: wordpress
    restart: always
    depends_on:
      - mariadb
    volumes:
      - wordpress_vol:/var/www/html
    networks:
      - inception_network
    env_file:
      - .env
    secrets:
      - mysql_database
      - mysql_password
      - mysql_user
      - wp_admin_email
      - wp_admin_password
      - wp_admin_user
      - wp_user_email
      - wp_user_password
      - wp_user

  nginx:
    build:
      context: ./requirements/nginx
    image: nginx
    container_name: nginx
    restart: always
    depends_on:
      - wordpress
    ports:
      # Exclusively expose HTTPS (443). HTTP (80) is strictly prohibited.
      - "443:443"
    volumes:
      - wordpress_vol:/var/www/html
    networks:
      - inception_network
    env_file:
      - .env

volumes:
  mariadb_vol:
    driver: local
    driver_opts:
      type: none
      device: /home/spacotto/data/mariadb
      o: bind
  wordpress_vol:
    driver: local
    driver_opts:
      type: none
      device: /home/spacotto/data/wordpress
      o: bind

networks:
  # Custom bridge network connecting all containers
  # Explicitly defined to comply with the prohibition of 'network: host' and 'links'
  inception_network:
    driver: bridge
